name: Build CV PDF

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    paths:
      - 'assets/cv.md'
      - 'css/cv.css'
      - 'scripts/**'
      - '.github/workflows/build-cv.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate HTML from Markdown
        run: |
          python3 scripts/generate_cv.py

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget fonts-liberation
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -fy install

      - name: Build PDF via headless Chrome
        run: |
          bash scripts/build_cv_pdf.sh

      - name: Commit updated CV assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(cv): auto-update HTML/PDF from cv.md'
          file_pattern: 'assets/cv.html assets/cv.pdf'
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
