name: Build CV PDF

permissions:
  contents: write

on:
  push:
    branches: [ main, master ]
    paths:
      - 'assets/cv.md'
      - 'css/cv.css'
      - 'scripts/**'
      - '.github/workflows/build-cv.yml'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate HTML from Markdown
        run: |
          python3 scripts/generate_cv.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: |
          npm i --no-save puppeteer@22

      - name: Export PDF with Puppeteer (no header/footer)
        run: |
          node scripts/export_pdf.mjs assets/cv.html assets/cv.pdf

      - name: Commit updated CV assets
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(cv): auto-update HTML/PDF from cv.md'
          file_pattern: 'assets/cv.html assets/cv.pdf'
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
